### PR TITLE
Adding a filter for the people tracker based on a map

### LINKED ISSUE #175: Add people tracker filter based on map
Inspired by the laser filter for the leg detector, this filter will either take the current map published on `/map` and exclude all detections that are not in free space, i.e. obstacles or unknown, or uses a custom map to do so. Similar to the abandoned `no_go_map` this `no_ppl_map` allows you to draw black areas into the map, where you won't accept any people tracks. This is useful if you have an environment that is prone to false positives in certain areas where equipment is standing around and persons are unlikely to appear. The node just takes all the tracker messages and filters them based on their `x,y` location in a simple map look-up.

This is basically done and this issue only serves as a reminder to myself to clean-up the code and open a PR once the HRI deadline is over.

### PR DESCRIPTION
**Pull request by cdondrup**
Closes #175 

Needs #169 merged

Changes made to `bayes_people_tracker`:
- Renamed directories inside `src` and `include` to reflect the project name and therefore have the headers installed correctly.
- Created a dedicated human marker class that is also used by the new filter to generate the markers.

Changes made to `bayes_people_tracker_logging`:
- Logs the filtered tracking results now

Changes made to `perception_people_launch`:
- The parameter `with_map_filter` has been renamed to `with_laser_filter` to reflect its functionality better.
- The `people_tracker_filter` is started by default. Using the map published on `/map`.

The `people_tracker_filter` works as described in issue #175 which means it filters the output of the tracker using a map. By default this is the map published on `/map`. Hence, this node listens to all the topics published by the `bayes_people_tracker` and filters out the tracks that are inside obstacles, unknown areas, or off the grid. Additionally, the filter can utilise its own map server and its own "no_people_map" which works similar to the old "no_go_map". Below is an example of a map I used for an experiment to only allow detections in the centre of our lab so I could stay in the black areas without interfeering and to prevent false positives from furniture:

map

In this map, every track that would result in the person being inside the black areas, is filtered out and only the tracks where the person is inside the free space are left.

The results are publish on:
- `/people_tracker_filter/positions` -> `bayes_people_tracker/PeopleTracker`
- `/people_tracker_filter/pose` -> `geometry_msgs/PoseStamped`: _closest person that might be a different one that in the unfiltered results._
- `/people_tracker_filter/pose_array` -> `geometry_msgs/PoseArray`
- `/people_tracker_filter/people` -> `people_msgs/People`
- `/people_tracker_filter/marker_array` -> `visualization_msgs/MarkerArray`

The filter is started by default when starting the people perception but like all the other components of the people perception pipeline, actually does not do any processing unless someone subscribes to one of its published topics. To start it with an especially created map, run:

```
roslaunch perception_people_launch people_tracker_robot.launch with_tracker_filter_map:=true tracker_filter_map:=my_map.yaml
```

The map is then publish under `/ppl_filter_map`. 

_Note: Since this node only filters the results, a person that goes into a black area and then leaves it again will have the same uuid if they have been tracked in the mean time. This might mean that a person vanishes in a "no_people_zone" and then re-appears._

I tested this on Linda and it will also work with the `people_tracker_emulator` in simulation.

If I remember correctly, @lucasb-eyer @PDuckworth  and @ferdianjovan voiced interest in this node, so please feel free to test it.

### CODE REVIEW

**Comment by cdondrup** [comment]
This failed due to #169 not being merged yet:

```
/var/lib/jenkins/workspace/pr-indigo-strands_perception_people/monitored_vcs/people_tracker_filter/src/filter.cpp:109:28: error: 'bayes_people_tracker::PeopleTracker' has no member named 'velocities'
                     pt_out.velocities.push_back(pt->velocities[i]);
```

Please retest after merge of #169

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
:-( @cdondrup ?

**Comment by cdondrup** [comment]
Not sure what happened. I rebased now... Let's see if that works.

**Comment by cdondrup** [comment]
Builds now.
